$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        381:{
            items:2
        },
        767:{
            items:3
        },
        1000:{
            items:5
        }
    }
})